# Generated by Django 3.1.4 on 2021-06-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
