# Generated by Django 3.1.4 on 2021-06-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawplayer', '0003_watchlater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlater',
            old_name='song_id',
            new_name='video_id',
        ),
    ]
