# Generated by Django 3.1.4 on 2021-06-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawplayer', '0004_auto_20210626_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlater',
        ),
    ]
