# Generated by Django 3.1.4 on 2021-06-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawplayer', '0007_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='trend',
            field=models.BooleanField(default=False),
        ),
    ]
