# Generated by Django 3.1.4 on 2021-06-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawplayer', '0010_auto_20210627_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='song',
            name='trend',
        ),
    ]
