# Generated by Django 3.1.4 on 2021-06-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawplayer', '0011_auto_20210627_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='trend',
            field=models.BooleanField(default=False),
        ),
    ]
