# Generated by Django 3.1.4 on 2021-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawplayer', '0013_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(default='New Playlist', max_length=1000),
        ),
    ]
