# Generated by Django 3.1.4 on 2021-07-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawplayer', '0014_playlist_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='thumbnail',
            field=models.ImageField(default='/rawplayer/musicphoto.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(default='New Playlist', max_length=1000, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
    ]
